### ISSUE TITLE
Query ::

### ISSUE THREAD

**Issue by MxResearch** [0x71/cuckoo-linux#1]
hello devloper..

i tried your cuckoo-linux.. but it only performs static analysis..  what about dynamic analysis ??

can you please explain me.. dynamic analysis process of malware in linux platform, like analysis of ELF or .deb file..

thanking youu

**Comment by 0x71** [comment]
Hi,

what kind of Linux guest are you using? 

Dynamic analysis is based on python-ptrace and some additional dependencies. For debian based systems these packages should work for you:

**sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install build-essential ssh -y
sudo apt-get install python2.7-dev python-setuptools python-pip -y
sudo apt-get install libyaml-dev
sudo easy_install watchdog python-ptrace
sudo apt-get install python-bson
sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0**

I just added a [INSTALL.md](https://github.com/0x71/cuckoo-linux/blob/master/INSTALL.md) with a step by step documentation on how I configured my cuckoo host and guest environment.
